# Generated by Django 5.0.6 on 2024-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0002_commodity_country_cncode_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='quota_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
