# Generated by Django 5.0.6 on 2024-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0003_licence_quota_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='licence_validity',
            field=models.DateField(),
        ),
    ]
