# Generated by Django 5.0.6 on 2024-06-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0004_alter_licence_licence_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqLicence',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_quantity', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
                ('request_date', models.DateField()),
                ('licence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appka.licence')),
            ],
        ),
    ]
