# Generated by Django 5.0.6 on 2024-06-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0005_reqlicence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqlicence',
            old_name='licence_id',
            new_name='licence',
        ),
    ]
